### PR TITLE
updated navbar, added employee section, updated footer, 'updated hero…

### PR DESCRIPTION
**Pull request by anasgee**
… updated hero section section with join now button...
plz accept it.
I hope It will look better than before.

### CODE REVIEW

**Comment by BossG21** [comment]
can u send me screen shots of your work
??

**Comment by anasgee** [comment]
yes sure/....

**Comment by anasgee** [comment]
Screenshot (20)
Screenshot (21)

**Comment by BossG21** [comment]
oh! Great work sir...

**Pull request merged**
